version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: M3*.pL2A45p\
      POSTGRES_USER: postgres
      POSTGRES_DB: Rest-API
      TZ: America/Sao_Paulo
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - 5432:5432
    volumes:
      - ./src/infra/database/init.sql:/docker-entrypoint-initdb.d/init.sql